declare namespace NodeJS {
  export interface ProcessEnv {
    NEXT_PUBLIC_API_KEY: string;
    NEXT_PUBLIC_EMAIL_REGISTRATION_SERVICE: string;
    NEXT_PUBLIC_EMAIL_REGISTRATION_TEMPLATE: string;
    NEXT_PUBLIC_CONTACT_US_FORM_TEMPLATE: string;
    NEXT_PUBLIC_PAYPAL_CLIENT_ID: string;
    NEXT_PUBLIC_TYPESENSE_HOST: string;
    NEXT_PUBLIC_TYPESENSE_API_KEY: string;
  }
}
